spring:
  application:
    name: user-service
  r2dbc:
    username: pguser
    password: pgpassword
    url: ${PG_DATABASE_URL:r2dbc:postgresql://localhost:5499/auth}
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: ${FLYWAY_DB_URL:jdbc:postgresql://localhost:5499/auth}
  jwt:
    secret: ${jwt_secret}
    expiration: 2_592_000_000 #30Days
    jwt-access-expiration: 3_600_000
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.ds.user_service.model.dto.analytics.AnalyticsEvent"
        spring.json.use.type.headers: false

analytics:
  category_topic: analytics.category
  source_topic: analytics.source

uri:
  embedding_uri: ${AI_SERVICE_HOST:http://localhost:8999} #TODO

logging:
  level:
    # Core Spring Security
    org.springframework.security: TRACE
    org.springframework.security.web: DEBUG
    org.springframework.security.web.server: DEBUG
    org.springframework.security.authorization: TRACE
    org.springframework.security.authentication: DEBUG
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8901/eureka}
