logging:
  level:
    org.springframework.core.env: DEBUG
    org.springframework.boot.context.config: DEBUG
spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8910"