spring:
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: enriched-news-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ds.recommendationservice.models.EnrichedNewsPayload
        spring.json.use.type.headers: false
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8901/eureka
news:
  enriched_news_topic: news.enriched
  recommendation_created_topic: recommendation.created

uri:
  embedding_uri: http://localhost:8999
  user_service: http://localhost:8080
  news_service: http://localhost:8902
